In [10]:
pip list numpy

Package                           Version
--------------------------------- ------------------
aiobotocore                       2.12.3
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-catalogs                 0.2.0
anaconda-client                   1.12.3
anaconda-cloud-auth               0.5.1
anaconda-navigator                2.6.3
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.2.0
appdirs                           1.4.4
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
astroid                           2.14.2
astropy                           6.1.3
astropy-iers-data

In [32]:
v = np.empty(10)

In [18]:
v = np.array([55, 17, 29, 45, 21, 86])

print("So chieu:", end=" ")
print(v.ndim)
print("So phan tu:", end=" ")
print(v.size)

So chieu: 1
So phan tu: 6


In [27]:
v = np.random.randint(0,9,15)
print(v)
v[4]

[1 0 4 3 5 1 1 0 0 3 1 2 0 5 1]


5

In [34]:
v = np.random.randint(0,9,(3,4))
print("So chieu:", end=" ")
print(v.ndim)

print("So phan tu:", end=" ")
print(v.size)


So chieu: 2
So phan tu: 12


In [53]:
v = np.array([[5 ,10,21],
             [11,23,18],
             [22,19,35],
             [96,22,26]])
print("So chieu:", end=" ")
print(v.ndim)
print(v)

print("So hang:",end=" ")
print(v.shape[0])

print("So cot:",end=" ")
print(v.shape[1])
print("Lay hang 2,3")
print(v[1])
print(v[2])

print("===vector cot 3")
v1 = v[:,2]
print(v1)

print("Vector nho")
v2 = v[1:4,1:3]
print(v2)
print()
print("Doi gia tri")
v[3,1] = 30
print(v)

So chieu: 2
[[ 5 10 21]
 [11 23 18]
 [22 19 35]
 [96 22 26]]
So hang: 4
So cot: 3
Lay hang 2,3
[11 23 18]
[22 19 35]
===vector cot 3
[21 18 35 26]
Vector nho
[[23 18]
 [19 35]
 [22 26]]

Doi gia tri
[[ 5 10 21]
 [11 23 18]
 [22 19 35]
 [96 30 26]]


In [69]:
v = np.arange(10,20)
print(v)
print("So phan tu:", end=" ")
print(v.size)
v1 =v.reshape(2,5)
print(v1)
print("So chieu vector moi:", end=" ")
print(np.ndim(v1))


[10 11 12 13 14 15 16 17 18 19]
So phan tu: 10
[[10 11 12 13 14]
 [15 16 17 18 19]]
So chieu vector moi: 2


In [122]:
v = np.array([87, 46, 87, 62, 11, 32])
print(v)
print("Max =", end=" ")
print(np.max(v))
print("Min =", end=" ")
print(np.min(v))
v = np.sort(v)
print(v)
print(v[0::2])
print(v[3],end=" ")
print("la so", end=" ")
if v[3] %2==0:
    print("Chan")
else:
    print("le")

c = np.sum(v%2==0)
print("so luong so chan tron mang =",c)
print("Tong cac phan tu =", np.sum(v))
print("mean (trung binh) =", round(np.mean(v),2))
print("median (trung vi) =", np.median(v))


mean_v = np.mean(v)
print(v)
v1 = v[v!=62]
print(v1)

print(mean_v)
v1[v1==87] = mean_v
print(v1)


[87 46 87 62 11 32]
Max = 87
Min = 11
[11 32 46 62 87 87]
[11 46 87]
62 la so Chan
so luong so chan tron mang = 3
Tong cac phan tu = 325
mean (trung binh) = 54.17
median (trung vi) = 54.0
[11 32 46 62 87 87]
[11 32 46 87 87]
54.166666666666664
[11 32 46 54 54]


In [169]:
m = np.array(  [[[ 5,10,21],
                 [11,23,18],
                 [22,19,35]],
                
                [[50,10,41],
                 [61,23,28],
                 [42,11,25]],
                
                [[96,22,26],
                 [87,56,23],
                 [90,75,32]]
               ])


print(m)
print()
print(m[0,1:3,:])
mean_1 = np.mean(m[0])
print(mean_1)

m[1,:,0] = mean_1
print()
print(m)
print("sum ma tran 3 =", np.sum(m[2]))

m[2,2,:] = -1
print(m)

print("Ma tran moi tu matrix 2")
matrix_a = m[1]
print(matrix_a)
print("So chieu:", np.ndim(matrix_a))

matrix_a = np.reshape(matrix_a,9)
matrix_a = np.append(matrix_a, 45)
matrix_a = np.insert(matrix_a,0, 99)
print(matrix_a)


print(m.tolist())

[[[ 5 10 21]
  [11 23 18]
  [22 19 35]]

 [[50 10 41]
  [61 23 28]
  [42 11 25]]

 [[96 22 26]
  [87 56 23]
  [90 75 32]]]

[[11 23 18]
 [22 19 35]]
18.22222222222222

[[[ 5 10 21]
  [11 23 18]
  [22 19 35]]

 [[18 10 41]
  [18 23 28]
  [18 11 25]]

 [[96 22 26]
  [87 56 23]
  [90 75 32]]]
sum ma tran 3 = 507
[[[ 5 10 21]
  [11 23 18]
  [22 19 35]]

 [[18 10 41]
  [18 23 28]
  [18 11 25]]

 [[96 22 26]
  [87 56 23]
  [-1 -1 -1]]]
Ma tran moi tu matrix 2
[[18 10 41]
 [18 23 28]
 [18 11 25]]
So chieu: 2
[99 18 10 41 18 23 28 18 11 25 45]
[[[5, 10, 21], [11, 23, 18], [22, 19, 35]], [[18, 10, 41], [18, 23, 28], [18, 11, 25]], [[96, 22, 26], [87, 56, 23], [-1, -1, -1]]]


In [186]:
ds = [45, 52, 30, 22, 19, 78, 22, 55]
v = np.array(ds)
v1 = np.array(ds)
print(ds)
print(v)
print("So phan tu =", v.size)
print("So chieu =", v.ndim)
v = np.reshape(v,(2,4))
print()
print(v)
v = np.reshape(v,(4,2))
print()
print(v)
print()
print(v1[1::2])

[45, 52, 30, 22, 19, 78, 22, 55]
[45 52 30 22 19 78 22 55]
So phan tu = 8
So chieu = 1

[[45 52 30 22]
 [19 78 22 55]]

[[45 52]
 [30 22]
 [19 78]
 [22 55]]

[52 22 78 55]


In [239]:

sv = np.loadtxt("sinhvien.txt",skiprows=1, dtype=str)
print(sv)

#sv = np.insert(sv, 0, ['STT','HOTEN','TUOI'], axis=0)

print()
print(sv)
tb_tuoi = np.mean(sv[:,2].astype(int))
print("Tuoi trung binh =",tb_tuoi)

print("So luong sinh vien = ", sv.shape[0])

#np.savetxt("sinhvien.txt", sv, fmt='%s', delimiter=" ")

[['1' 'Huynh' '23']
 ['2' 'Lan' '21']]

[['1' 'Huynh' '23']
 ['2' 'Lan' '21']]
Tuoi trung binh = 22.0
So luong sinh vien =  2
